name: Create our Weekly Meeting notes issue
on:
  schedule:
    - cron: '* * * * *'
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: titanicboyke/data@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: ./data/migration
