name: Update file
on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        name: 'Update file'
        env:
          CONTRIB_REPOSITORY: 'titanicboyke/data'
          CONTRIB_OUTPUT_FILE: 'migration'
      - name: Update resources
        uses: titanicboyke/action-update-file@main
        with:
          file-path: 'migration'
          commit-msg: Update Contributors
          github-token: ${{ secrets.GITHUB_TOKEN }}
