name: Datetime of Workflow
on:
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: "* * * * *"
    
    branches:
      - main
    workflow_dispatch:
jobs:
  workflow-date:
    name: Update the datetime of workflow in the README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update with Datetime of Workflow
        uses: titanicboyke/data/migration@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # date_format: '%a  %d %b %Y  %H:%M:%S%Z'
          # timezone: 'UTC'
          # tag: 'DEFAULT-TAG'
          # markdown_path: './data/migration'
