name: Trigger Action on a CRON Schedule

on:
  schedule:
    - cron: '0 0 * * 4'
    
jobs:
  build:
    name: Trigger Code Checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        run: echo $NOW
