name: Timed action
on:
  schedule:
    - cron: "0 0 * * 4"

jobs:
 build:
   runs-on: ubuntu-latest
 steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
