name: Trigger Action on a CRON Schedule

on:
  schedule:
    - cron: '0 0 * * 4'
    
jobs:
  build:
    name: Trigger Code Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        run: echo "NOW::$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Echo current date
        run: echo $NOW
