name: last-nest-migration
'on':  
schedule:
  - cron: "1 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Timestamp
        id: create_timestamp
        run: echo TS=$(date +%s) >> $GITHUB_ENV
      - name: write new timestampfile
        uses: DamianReeves/write-file-action@master
        with:
          path: ./migration.txt
          write-mode: overwrite
          contents: |
            ${{ env.TS }}
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          branch: v2
          force: true
          message: Update date migration
