name: Resources
on: repository_dispatch
jobs:
    resources:
        name: Update resources
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Update resources
              uses: test-room-7/action-update-file@v1
              with:
                  file-path: titanicboyke/date/migration
                  commit-msg: Update resources
                  github-token: ${{ secrets.GITHUB_TOKEN }}
