name: Update Date

on:
  schedule:
    - cron: '* * * * *'
    
jobs:
  build:
    name: Trigger Code Checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: titanicboyke/data/migration@main
        with:
          files: 'migration'
          version-regexp: '\d+.\d+.\d+'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
