name: Datetime of Workflow
on:
  push:
    branches:
      - main
    workflow_dispatch:
jobs:
  workflow-date:
    name: Update the datetime of workflow in the README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 

      - name: Update with Datetime of Workflow
        uses: titanicboyke/workflow-date@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # date_format: '%a  %d %b %Y  %H:%M:%S%Z'
          # timezone: 'UTC'
          # tag: 'DEFAULT-TAG'
          # markdown_path: './migration'
          # commit_branch: 'main'
          # commit_username: 'github-actions[bot]'
          # commit_email: 'github-actions[bot]@users.noreply.github.com'
          # commit_message: '🚀 Datetime of Workflow Updated'
